# Generated by Django 5.0 on 2025-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('DRIVING', 'Driving'), ('PUTTING', 'Putting'), ('CHIPPING', 'Chipping'), ('IRON_PLAY', 'Iron Play'), ('COURSE_MANAGEMENT', 'Course Management')], max_length=50)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Beginner-Intermediate'), (3, 'Intermediate'), (4, 'Intermediate-Advanced'), (5, 'Advanced')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='drivingrange',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='drivingrange',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drivingrange',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivingrange',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
