# Generated by Django 4.2.22 on 2025-06-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_round_shareable_link_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveIntegerField()),
                ('par', models.PositiveIntegerField()),
                ('yardage', models.PositiveIntegerField(blank=True, null=True)),
                ('handicap_index', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='golf_app.course')),
            ],
            options={
                'ordering': ['hole_number'],
                'unique_together': {('course', 'hole_number')},
            },
        ),
    ]
